routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('register', 'HomeController@redirectToLogin')->name('register');
Route::post('register', 'HomeController@redirectToLogin')->name('register');

Route::middleware(['auth'])->group(function () {

    Route::get('/', 'HomeController@index')->name('home');

    Route::get('cars/expenses', 'CarExpenseController@all')->name('cars.expenses');
    Route::get('cars/{car}/expenses/{expense}/verified', 'CarExpenseController@verified')->name('cars.expenses.verified');
    Route::get('receivedOrders/{receivedOrder}/issuedOrders/{issuedOrder}/freights/{freight}/replicate', 'ReceivedOrderIssuedOrderFreightController@replicate')->name('receivedOrders.issuedOrders.freights.replicate');
    Route::get('receivedOrders/{receivedOrder}/shipments/{shipment}/freights/{freight}/replicate', 'ReceivedOrderShipmentFreightController@replicate')->name('receivedOrders.shipments.freights.replicate');
    Route::get('issuedOrders/{issuedOrder}/pdfOpen', 'IssuedOrderController@pdfOpen')->name('issuedOrders.pdfOpen');
    Route::get('issuedOrders/{issuedOrder}/pdfDownload', 'IssuedOrderController@pdfDownload')->name('issuedOrders.pdfDownload');
    Route::get('invoices/{invoice}/pdfOpen', 'InvoiceController@pdfOpen')->name('invoices.pdfOpen');
    Route::get('invoices/{invoice}/pdfDownload', 'InvoiceController@pdfDownload')->name('invoices.pdfDownload');
    Route::get('settings/profile', 'UserController@profile')->name('settings.profile');

    Route::resources([
        'cars' => 'CarController',
        'cars.expenses' => 'CarExpenseController',
        'expenses' => 'ExpenseController',
        'clients' => 'ClientController',
        'carriers' => 'CarrierController',
        'drivers' => 'DriverController',
        'drivers.deposits' => 'DriverDepositController',
        'invoices' => 'InvoiceController',
        'invoices.details' => 'InvoiceDetailController',
        'trips' => 'TripController',
        'trips.expenses' => 'TripExpenseController',
        'trips.shipments' => 'TripShipmentController',
        'trips.deposits' => 'TripDepositController',
        'receivedOrders' => 'ReceivedOrderController',
        'issuedOrders' => 'IssuedOrderController',
        'receivedOrders.freights' => 'ReceivedOrderFreightController',
        'receivedOrders.shipments' => 'ReceivedOrderShipmentController',
        'receivedOrders.shipments.freights' => 'ReceivedOrderShipmentFreightController',
        'receivedOrders.issuedOrders' => 'ReceivedOrderIssuedOrderController',
        'receivedOrders.issuedOrders.freights' => 'ReceivedOrderIssuedOrderFreightController',

    ]);


    Route::prefix('data')->name('data.')->group(function () {
        Route::get('cars', 'CarController@data')->name('cars');
        Route::get('clients', 'ClientController@data')->name('clients');
        Route::get('clients/{client}', 'ClientController@single')->name('client');
        Route::get('carriers', 'CarrierController@data')->name('carriers');
        Route::get('drivers', 'DriverController@data')->name('drivers');
        Route::get('invoices', 'InvoiceController@data')->name('invoices');
        Route::get('invoices/{invoice}/receivedOrders/', 'InvoiceDetailController@dataReceivedOrdersNoInvoice')->name('receivedOrdersNoInvoice');
        Route::post('invoices/{invoice}/receivedOrders/', 'InvoiceDetailController@attachReceivedOrderToInvoice')->name('attachDetails');
        Route::get('invoice/max', 'HomeController@null')->name('invoice.max');
        Route::get('invoice/max/{series}', 'invoiceController@maxNumber')->name('invoice.max.number');
        Route::get('exchange', 'HomeController@null')->name('exchange');
        Route::get('exchange/{day}/{month}/{year}', 'invoiceController@exchangeRate')->name('exchangeRate');
        Route::get('drivers/{driver}/deposits', 'DriverDepositController@data')->name('drivers.deposits');

        //trips

        Route::prefix('trips')->name('trips.')->group(function () {

            Route::get('', 'TripController@data')->name('index');

            Route::prefix('{trip}')->group(function () {

                //shipments

                Route::get('shipments', 'TripShipmentController@shipmentsData')->name('shipments');
                Route::get('carShipments', 'TripShipmentController@carShipmentsData')->name('carShipments');
                Route::post('detachShipments', 'TripShipmentController@detachShipments')->name('detachShipments');
                Route::post('attachShipments', 'TripShipmentController@attachShipments')->name('attachShipments');

                //deposits

                Route::get('deposits', 'TripDepositController@depositsData')->name('deposits');
                Route::get('driverDeposits', 'TripDepositController@driverDepositsData')->name('driverDeposits');
                Route::post('detachDeposits', 'TripDepositController@detachDeposits')->name('detachDeposits');
                Route::post('attachDeposits', 'TripDepositController@attachDeposits')->name('attachDeposits');

                //expenses
                Route::get('expenses', 'TripExpenseController@data')->name('expenses');
            });
        });

        Route::get('cars/expenses', 'CarExpenseController@dataAll')->name('cars.all.expenses');
        Route::get('cars/{car}/expenses', 'CarExpenseController@data')->name('cars.expenses');

        Route::get('drivers/{driver}/tripDeposits', 'DriverController@shipmentsData')->name('driver.deposits');
        Route::post('drivers/{driver}/tripDeposits/{trip}', 'DriverController@shipmentsTrip')->name('driver.deposits.trip');
        Route::get('expenses', 'ExpenseController@data')->name('expenses');
        Route::get('receivedOrders', 'ReceivedOrderController@data')->name('receivedOrders');
        Route::get('issuedOrders', 'IssuedOrderController@data')->name('issuedOrders');
        Route::get('settings/countries', 'CountryController@data')->name('settings.countries');
        Route::get('settings/users', 'UserController@data')->name('settings.users');
    });

    Route::prefix('log')->name('log.')->group(function () {

        Route::get('receivedOrders/{receivedOrder}', 'ReceivedOrderController@log')->name('receivedOrders');

    });

//    Route::resource('car.expenses', 'CarExpenseController');
//    Route::resource('v', 'ReceivedOrderController');
    Route::resource('settings/countries', 'CountryController', ['as' => 'settings']);
    Route::resource('settings/users', 'UserController', ['as' => 'settings']);
//    Route::resource('receivedOrders.freights', 'ReceivedOrderFreightController');

    Route::get('mail', 'DevController@mail')->name('mail');
//    Route::get('issuedOrders', 'DevController@issuedOrders')->name('issuedOrders');
    Route::get('pdf', 'DevController@pdf')->name('pdf');
    Route::get('db2', 'DevController@db2')->name('db2');
//    Route::get('api', 'DevController@api')->name('api');
    Route::get('test', 'DevController@test')->name('test');
    Route::get('test2', 'DevController@test2')->name('test2');
    Route::get('rate', 'DevController@rate')->name('rate');
    Route::get('form', 'DevController@form')->name('form');
    Route::post('form', 'DevController@post')->name('form');

});

app/Carrier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;


class Carrier extends Model
{
    //
    use LogsActivity;

    protected static $logAttributes = ['*'];

    protected $fillable = [
        'name',
        'cif',
        'orc',
        'country_id',
        'address',
        'bank',
        'iban',
        'swift',
        'phone',
        'email',
        'contact',
    ];

    public function country()
    {
        return $this->belongsTo('App\Country');
    }
}

app/Http/Controllers/CarrierController.php
<?php

namespace App\Http\Controllers;

use App\Carrier;
use App\Country;
use App\Http\Requests\AddCarrierRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\DataTables;

class CarrierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('carriers.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $countries = Country::orderBy('name')->get();

        return view('carriers.create', compact('countries'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddCarrierRequest $request)
    {
        //
        $client = Carrier::create($request->all());

        return redirect(route('carriers.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Carrier  $carrier
     * @return \Illuminate\Http\Response
     */
    public function show(Carrier $carrier)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Carrier  $carrier
     * @return \Illuminate\Http\Response
     */
    public function edit(Carrier $carrier)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Carrier  $carrier
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Carrier $carrier)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Carrier  $carrier
     * @return \Illuminate\Http\Response
     */
    public function destroy(Carrier $carrier)
    {
        //
    }

    public function data()
    {
        //
//        $expenses = DB::table('expenses')->join('cars', 'expenses.car_id', 'cars.id')->select('cars.plate', 'expenses.name', 'expenses.date', 'expenses.cost');

//        $expenses = DB::table('expenses')->join('cars', 'expenses.car_id', 'cars.id')->select('cars.plate', 'expenses.name', 'expenses.date', 'expenses.cost');

        $carriers = DB::table('carriers')
            ->join('countries', 'carriers.country_id', 'countries.id')
            ->select('carriers.name', 'carriers.cif', 'countries.name as country', 'carriers.phone');

//            dd($clients->get());

        return Datatables::of($carriers)
            ->make(true);
    }
}

resources/views/carriers/create.blade.php
@extends('layouts.main')

@section('head-inject')
  <!-- DataTables -->
  <link rel="stylesheet" href="/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endsection

@section('content')

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Flota
      <small>Lista masini</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="#">Forms</a></li>
      <li class="active">General Elements</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Masina noua</h3>
          </div>
          <!-- /.box-header -->
          <!-- form start -->
          <form role="form" method="POST" action="{{ route('cars.store') }}">
            {{ csrf_field() }}
            <div class="box-body">
              @if ($errors->any())
                <div class="alert alert-danger">
                  <ul>
                    @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                    @endforeach
                  </ul>
                </div>
              @endif
              <div class="form-group">
                <label for="inputPlate">Numar auto</label>
                <input type="text" class="form-control" id="inputPlate" placeholder="B01ERU" name="plate" required>
              </div>
              <div class="form-group">
                <label for="inputDescription">Descriere</label>
                <textarea id="inputDescription" class="form-control" rows="3" placeholder="Descriere ..." name="description"></textarea>
              </div>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Salveaza</button>
            </div>
          </form>
        </div>
      </div>
        <!-- /.box -->

    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->

@endsection

@section('footer-inject')

@endsection

resources/views/carriers/index.blade.php
@extends('layouts.main')

@push('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endpush

@section('content')

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Flota
      <small>Control panel</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Dashboard</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Transportatori</h3>

            <div>
                <a href="{{ route('carriers.create') }}" class="btn btn-success">Adauga transportator</a>
            </div>

          </div>
          <!-- /.box-header -->
          <div class="box-body" style="white-space:nowrap;">


            <table class="table table-bordered" id="cars-table" width="100%">
              <thead>
              <tr>
                <th>Nume</th>
                <th>CUI</th>
                <th>Tara</th>
                <th>Telefon</th>
              </tr>
              </thead>
            </table>

          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->

@endsection

@push('scripts')

  <!-- DataTables -->
  <script src="/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

  <!-- page script -->
  {{--<script>--}}
      {{--$(function () {--}}
          {{--// $('#example1').DataTable()--}}
          {{--$('#example1').DataTable({--}}
              {{--'paging'      : true,--}}
              {{--'lengthChange': false,--}}
              {{--// 'searching'   : false,--}}
              {{--// "columns": [--}}
              {{--//     { "searchable": false },--}}
              {{--//     null,--}}
              {{--//     null,--}}
              {{--//     null,--}}
              {{--//     null--}}
              {{--// ],--}}
              {{--'ordering'    : true,--}}
              {{--'info'        : true,--}}
              {{--'autoWidth'   : false,--}}
              {{--// 'filtering'   : true--}}
          {{--})--}}
      {{--})--}}
  {{--</script>--}}

  <script>
      $(function() {
          $('#cars-table').DataTable({
              // responsive: true,
              processing: true,
              serverSide: true,
              ajax: '{!! route('data.carriers') !!}',
              columns: [
                  { data: 'name', name: 'name' },
                  { data: 'cif', name: 'cif' },
                  { data: 'country', name: 'countries.name' },
                  { data: 'phone', name: 'phone' },
              ],
              "scrollX": true,
              "order": [[ 0, "asc" ]],
              // columnDefs: [
              //     { responsivePriority: 1, targets: 0 },
              //     { responsivePriority: 2, targets: -1 }
              // ]
          });
      });
  </script>

@endpush