routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('register', 'HomeController@redirectToLogin')->name('register');
Route::post('register', 'HomeController@redirectToLogin')->name('register');

Route::middleware(['auth'])->group(function () {

    Route::get('/', 'HomeController@index')->name('home');

    Route::get('cars/expenses', 'CarExpenseController@all')->name('cars.expenses');
    Route::get('cars/{car}/expenses/{expense}/verified', 'CarExpenseController@verified')->name('cars.expenses.verified');
    Route::get('receivedOrders/{receivedOrder}/issuedOrders/{issuedOrder}/freights/{freight}/replicate', 'ReceivedOrderIssuedOrderFreightController@replicate')->name('receivedOrders.issuedOrders.freights.replicate');
    Route::get('receivedOrders/{receivedOrder}/shipments/{shipment}/freights/{freight}/replicate', 'ReceivedOrderShipmentFreightController@replicate')->name('receivedOrders.shipments.freights.replicate');
    Route::get('issuedOrders/{issuedOrder}/pdfOpen', 'IssuedOrderController@pdfOpen')->name('issuedOrders.pdfOpen');
    Route::get('issuedOrders/{issuedOrder}/pdfDownload', 'IssuedOrderController@pdfDownload')->name('issuedOrders.pdfDownload');
    Route::get('invoices/{invoice}/pdfOpen', 'InvoiceController@pdfOpen')->name('invoices.pdfOpen');
    Route::get('invoices/{invoice}/pdfDownload', 'InvoiceController@pdfDownload')->name('invoices.pdfDownload');
    Route::get('settings/profile', 'UserController@profile')->name('settings.profile');

    Route::resources([
        'cars' => 'CarController',
        'cars.expenses' => 'CarExpenseController',
        'expenses' => 'ExpenseController',
        'clients' => 'ClientController',
        'carriers' => 'CarrierController',
        'drivers' => 'DriverController',
        'drivers.deposits' => 'DriverDepositController',
        'invoices' => 'InvoiceController',
        'invoices.details' => 'InvoiceDetailController',
        'trips' => 'TripController',
        'trips.expenses' => 'TripExpenseController',
        'trips.shipments' => 'TripShipmentController',
        'trips.deposits' => 'TripDepositController',
        'receivedOrders' => 'ReceivedOrderController',
        'issuedOrders' => 'IssuedOrderController',
        'receivedOrders.freights' => 'ReceivedOrderFreightController',
        'receivedOrders.shipments' => 'ReceivedOrderShipmentController',
        'receivedOrders.shipments.freights' => 'ReceivedOrderShipmentFreightController',
        'receivedOrders.issuedOrders' => 'ReceivedOrderIssuedOrderController',
        'receivedOrders.issuedOrders.freights' => 'ReceivedOrderIssuedOrderFreightController',

    ]);


    Route::prefix('data')->name('data.')->group(function () {
        Route::get('cars', 'CarController@data')->name('cars');
        Route::get('clients', 'ClientController@data')->name('clients');
        Route::get('clients/{client}', 'ClientController@single')->name('client');
        Route::get('carriers', 'CarrierController@data')->name('carriers');
        Route::get('drivers', 'DriverController@data')->name('drivers');
        Route::get('invoices', 'InvoiceController@data')->name('invoices');
        Route::get('invoices/{invoice}/receivedOrders/', 'InvoiceDetailController@dataReceivedOrdersNoInvoice')->name('receivedOrdersNoInvoice');
        Route::post('invoices/{invoice}/receivedOrders/', 'InvoiceDetailController@attachReceivedOrderToInvoice')->name('attachDetails');
        Route::get('invoice/max', 'HomeController@null')->name('invoice.max');
        Route::get('invoice/max/{series}', 'invoiceController@maxNumber')->name('invoice.max.number');
        Route::get('exchange', 'HomeController@null')->name('exchange');
        Route::get('exchange/{day}/{month}/{year}', 'invoiceController@exchangeRate')->name('exchangeRate');
        Route::get('drivers/{driver}/deposits', 'DriverDepositController@data')->name('drivers.deposits');

        //trips

        Route::prefix('trips')->name('trips.')->group(function () {

            Route::get('', 'TripController@data')->name('index');

            Route::prefix('{trip}')->group(function () {

                //shipments

                Route::get('shipments', 'TripShipmentController@shipmentsData')->name('shipments');
                Route::get('carShipments', 'TripShipmentController@carShipmentsData')->name('carShipments');
                Route::post('detachShipments', 'TripShipmentController@detachShipments')->name('detachShipments');
                Route::post('attachShipments', 'TripShipmentController@attachShipments')->name('attachShipments');

                //deposits

                Route::get('deposits', 'TripDepositController@depositsData')->name('deposits');
                Route::get('driverDeposits', 'TripDepositController@driverDepositsData')->name('driverDeposits');
                Route::post('detachDeposits', 'TripDepositController@detachDeposits')->name('detachDeposits');
                Route::post('attachDeposits', 'TripDepositController@attachDeposits')->name('attachDeposits');

                //expenses
                Route::get('expenses', 'TripExpenseController@data')->name('expenses');
            });
        });

        Route::get('cars/expenses', 'CarExpenseController@dataAll')->name('cars.all.expenses');
        Route::get('cars/{car}/expenses', 'CarExpenseController@data')->name('cars.expenses');

        Route::get('drivers/{driver}/tripDeposits', 'DriverController@shipmentsData')->name('driver.deposits');
        Route::post('drivers/{driver}/tripDeposits/{trip}', 'DriverController@shipmentsTrip')->name('driver.deposits.trip');
        Route::get('expenses', 'ExpenseController@data')->name('expenses');
        Route::get('receivedOrders', 'ReceivedOrderController@data')->name('receivedOrders');
        Route::get('issuedOrders', 'IssuedOrderController@data')->name('issuedOrders');
        Route::get('settings/countries', 'CountryController@data')->name('settings.countries');
        Route::get('settings/users', 'UserController@data')->name('settings.users');
    });

    Route::prefix('log')->name('log.')->group(function () {

        Route::get('receivedOrders/{receivedOrder}', 'ReceivedOrderController@log')->name('receivedOrders');

    });

//    Route::resource('car.expenses', 'CarExpenseController');
//    Route::resource('v', 'ReceivedOrderController');
    Route::resource('settings/countries', 'CountryController', ['as' => 'settings']);
    Route::resource('settings/users', 'UserController', ['as' => 'settings']);
//    Route::resource('receivedOrders.freights', 'ReceivedOrderFreightController');

    Route::get('mail', 'DevController@mail')->name('mail');
//    Route::get('issuedOrders', 'DevController@issuedOrders')->name('issuedOrders');
    Route::get('pdf', 'DevController@pdf')->name('pdf');
    Route::get('db2', 'DevController@db2')->name('db2');
//    Route::get('api', 'DevController@api')->name('api');
    Route::get('test', 'DevController@test')->name('test');
    Route::get('test2', 'DevController@test2')->name('test2');
    Route::get('rate', 'DevController@rate')->name('rate');
    Route::get('form', 'DevController@form')->name('form');
    Route::post('form', 'DevController@post')->name('form');

});

app/Invoice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;


class Invoice extends Model
{
    //
    use LogsActivity;

    protected static $logAttributes = ['*'];

    protected static $logOnlyDirty = true;

    protected $casts = [
        'delegate' => 'array',
        'buyer' => 'array',
        'details' => 'array',
    ];

    protected $fillable = [
        'series',
        'number',
        'date',
        'client_id',
        'details',
        'total_ron',
        'total_eur',
        'exchange_rate',
        'vat',
        'discount',
        'due_date',
        'delegate',
        'user_id'
    ];


    public function setDateAttribute($value)
    {
        $date = \DateTime::createFromFormat('d/m/Y', $value);

        $this->attributes['date'] =  $date->format('Y-m-d');
    }

    public function getDateAttribute($value)
    {
        $date = \DateTime::createFromFormat('Y-m-d', $value);

        return $date->format('d/m/Y');
    }

    public function setDueDateAttribute($value)
    {
        $date = \DateTime::createFromFormat('d/m/Y', $value);

        $this->attributes['due_date'] =  $date->format('Y-m-d');
    }

    public function getDueDateAttribute($value)
    {
        $date = \DateTime::createFromFormat('Y-m-d', $value);

        return $date->format('d/m/Y');
    }

    public function client()
    {
        return $this->belongsTo('App\Client');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\ExchangeRate;
use App\Http\Requests\AddInvoiceRequest;
use App\Invoice;
use App\Option;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Barryvdh\DomPDF\Facade as PDF;


class InvoiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('invoices.index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        $clients = Client::orderBy('name')->get();
        $exchangeRate = ExchangeRate::whereDate('date', '<=', Carbon::now())->orderBy('date','desc')->first();
//dd($exchangeRate);
        return view('invoices.create', compact('clients', 'exchangeRate', 'numbers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddInvoiceRequest $request)
    {
        //
//        dd($request->all());
        $invoice = Invoice::create($request->all());
//        dd($invoice->date);
        $client = Client::findOrFail($invoice->client_id);
        $buyer = $client->toArray();
        $buyer['country'] = $client->country->name;

        $invoice->buyer = $buyer;
//        $invoice->supplier = 'kkt';

//        dd($invoice);
        $invoice->supplier = Option::where('key','header')->first()->value;
//        dd($invoice);
        $invoice->update();
        return redirect(route('invoices.show', [$invoice->id]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Invoice  $invoice
     * @return \Illuminate\Http\Response
     */
    public function show(Invoice $invoice)
    {
        //
//        dd($invoice->buyer['name']);
//$client = $invoice->client;
//        dd($invoice->client);
        return view('invoices.show', compact('invoice'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Invoice  $invoice
     * @return \Illuminate\Http\Response
     */
    public function edit(Invoice $invoice)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Invoice  $invoice
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Invoice $invoice)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Invoice  $invoice
     * @return \Illuminate\Http\Response
     */
    public function destroy(Invoice $invoice)
    {
        //
    }

    public function maxNumber($series){
        return Invoice::where('series', $series)->max('number')+1;
    }

    public function exchangeRate($day, $month, $year){
//        dd();
        return ExchangeRate::whereDate('date', '<=', $year.'-'.$month.'-'.$day)->orderBy('date','desc')->first();

    }

    public function data(){

        $invoices = Invoice::join('clients', 'invoices.client_id', 'clients.id')
            ->select('invoices.id', 'invoices.series', 'invoices.number', 'clients.name', 'invoices.date', 'invoices.total_ron', 'invoices.total_eur');

        return Datatables::of($invoices)
            ->addColumn('action', function ($invoice) {
//                dd($receivedOrder);
                return '<a href="'.route('invoices.show', [$invoice->id]).'" class="btn btn-xs btn"><i class="glyphicon glyphicon-file"></i> Deschide</a>';
            })
            ->filterColumn('date', function ($query, $keyword) {
                $query->whereRaw("DATE_FORMAT(invoices.date,'%d/%m/%Y') like ?", ["%$keyword%"]);
            })
            ->make(true);

    }

    public function pdfOpen(Invoice $invoice)
    {
        $header = Option::where('key','header')->first()->value;
//        return view('invoices.pdf', compact('invoice','header'));
        $pdf = PDF::loadView('invoices.pdf', compact('invoice','header'))->setPaper('a4', 'portrait');
        return $pdf->stream();
    }

    public function pdfDownload(Invoice $invoice)
    {
        $header = Option::where('key','header')->first()->value;
        $pdf = PDF::loadView('invoices.pdf', compact('invoice','header'))->setPaper('a4', 'portrait');
        return $pdf->download('factura-'.$invoice->series.'#'.$invoice->number.'.pdf');
    }
}

resources/views/invoices/create.blade.php
@extends('layouts.main')

@section('head-inject')
  <!-- DataTables -->
  <link rel="stylesheet" href="/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endsection

@section('content')

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Comenzi primite
      <small>Adauga comanda primita</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="#">Forms</a></li>
      <li class="active">General Elements</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Comanda primita</h3>
          </div>
          <!-- /.box-header -->
          <!-- form start -->
          <form role="form" method="POST" action="{{ route('invoices.store') }}">
            {{ csrf_field() }}
            <input type="hidden" id="client_id" name="client_id">
            <input type="hidden" id="client_id" name="user_id" value="{{ Auth::user()->id }}">
            <div class="box-body">
              @if ($errors->any())
                <div class="alert alert-danger">
                  <ul>
                    @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                    @endforeach
                  </ul>
                </div>
              @endif
              <div class="form-group">
                <div class="dropdown">
                  <button id="client-button" class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">*Selecteaza client
                    <span class="caret"></span></button>
                  <ul class="dropdown-menu" id="client-select">
                    <input class="form-control" id="myInput" type="text" placeholder="Cauta...">

                    @foreach($clients as $client)
                      <li id="{{ $client->id }}"><a href="#">{{ $client->name }}</a></li>
                    @endforeach

                  </ul>
                </div>
              </div>
              <div class="form-group">
                  <label for="series">*Seria</label>
                  <select class="form-control" id="series" name="series" required>
                      <option value>Alege seria</option>
                      <option value="LBM"@if(old('series')=='LBM') selected @endif>LBM</option>
                      <option value="LOY"@if(old('series')=='LOY') selected @endif>LOY</option>
                  </select>
                  </div>
              <div class="form-group">
                <label for="inputNumber">*Numar</label>
                <input type="text" class="form-control" id="inputNumber" placeholder="435" name="number" value="{{ old('number') }}" required>
              </div>
              <div class="form-group">
                <label for="date">*Data</label>
                <div class="input-group date">
                  <div class="input-group-addon">
                    <i class="fa fa-calendar"></i>
                  </div>
                  <input type="text" class="form-control pull-right" id="date" name="date" value="{{ old('date')?old('date'):now()->format('d/m/Y') }}" required>
                </div>
                <!-- /.input group -->
              </div>
              <div class="form-group">
                  <label for="due_date">*Scadenta</label>
                  <div class="input-group date">
                      <div class="input-group-addon">
                          <i class="fa fa-calendar"></i>
                      </div>
                      <input type="text" class="form-control pull-right" id="due_date" name="due_date" value="{{ old('date')?old('date'):now()->format('d/m/Y') }}" required>
                  </div>
                  <!-- /.input group -->
              </div>
              <div class="form-group">
                  <label for="inputExchangeRate">*Cur valutar 1 EUR =</label>
                  <input type="number" step="any" class="form-control" id="inputExchangeRate" placeholder="0"  value="{{ old('exchange_rate')?old('exchange_rate'):$exchangeRate->rate }}" name="exchange_rate" required>
              </div>
              <div class="form-group">
                  <label for="inputDiscount">*Discount %</label>
                  <input type="number" step="any" class="form-control" id="inputDiscount" placeholder="0"  value="{{ old('discount')?old('discount'):0 }}" name="discount" required>
              </div>
              <div class="form-group">
                  <label for="inputVat">*TVA %</label>
                  <input type="number" step="any" class="form-control" id="inputVat" placeholder="0"  value="{{ old('vat')?old('vat'):0 }}" name="vat" required>
              </div>
              <div class="form-group">
                  <label for="inputDelegateName">Numele delegatului</label>
                  <input type="text" class="form-control" id="inputDelegateName" placeholder="Posta sau Bobitza" value="{{ old('delegate.name') }}" name="delegate[name]" required>
              </div>
              <div class="form-group">
                  <label for="inputDelegateIdSeries">Serie buletin delegat</label>
                  <input type="text" class="form-control" id="inputDelegateIdSeries" placeholder="AS" value="{{ old('delegate.id_series') }}" name="delegate[id_series]">
              </div>
              <div class="form-group">
                  <label for="inputDelegateIdNumber">Numar buletin delegat</label>
                  <input type="text" class="form-control" id="inputDelegateIdNumber" placeholder="372133" value="{{ old('delegate.id_number') }}" name="delegate[id_number]">
              </div>
              <div class="form-group">
                  <label for="inputDelegateIdIssuer">Buletin emis de</label>
                  <input type="text" class="form-control" id="inputDelegateIdIssuer" placeholder="Pol. mun. Mioveni" value="{{ old('delegate.id_issuer') }}" name="delegate[id_issuer]">
              </div>
              <div class="form-group">
                  <label for="inputDelegateTransport">Mijloc transport</label>
                  <input type="text" class="form-control" id="inputDelegateTransport" placeholder="Taxi sau B81ERE" value="{{ old('delegate.transport') }}" name="delegate[transport]">
              </div>
              <div class="form-group">
                  <label for="inputDelegateDate">La data de</label>
                  <div class="input-group date">
                      <div class="input-group-addon">
                          <i class="fa fa-calendar"></i>
                      </div>
                      <input type="text" class="form-control pull-right" id="inputDelegateDate" name="delegate[date]" value="{{ old('delegate.date')?old('delegate.date'):now()->format('d/m/Y') }}">
                  </div>
                  <!-- /.input group -->
              </div>
              <div class="form-group">
                  <label for="inputDelegateTime">La Ora</label>
                  <input type="text" class="form-control" id="inputDelegateTime" placeholder="12:00" value="{{ old('delegate.time')?old('delegate.time'):date("H:i") }}" name="delegate[time]">
              </div>
            </div>

            <!-- /.box-body -->

            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Salveaza</button>
            </div>
          </form>
        </div>
      </div>
        <!-- /.box -->

    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->

@endsection

@push('css')

  <!-- bootstrap datepicker -->
  <link rel="stylesheet" href="/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
  {{--<!-- Bootstrap time Picker -->--}}
  {{--<link rel="stylesheet" href="/plugins/timepicker/bootstrap-timepicker.min.css">--}}


@endpush

@push('scripts')
  <!-- bootstrap datepicker -->
  <script src="/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
  {{--<!-- bootstrap time picker -->--}}
  {{--<script src="/plugins/timepicker/bootstrap-timepicker.min.js"></script>--}}

  <script>
      //Date picker
      $('#date').datepicker({
          format: 'dd/mm/yyyy',
          autoclose: true
      });
      $('#due_date').datepicker({
          format: 'dd/mm/yyyy',
          autoclose: true
      });
      $('#inputDelegateDate').datepicker({
          format: 'dd/mm/yyyy',
          autoclose: true
      });
  </script>

  <script>
      $(document).ready(function(){
          $("#myInput").on("keyup", function() {
              // console.log('ok');
              var value = $(this).val().toLowerCase();
              $(".dropdown-menu li").filter(function() {
                  $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
              });
          });
          $("#client-select li").click(function() {
              $("#client_id").val(this.id);
              $("#client-button").text($(this).find("a").text());
              $.getJSON( "{{ route('data.clients') }}/" + this.id, function( data ) {
                  $("#inputDiscount").val(data.discount);
                  $("#inputVat").val(data.vat);
              });
              // console.log($("#client-button").text("kkt"))
                  //= ($(this).find("a").text());
              // $("#client-button").html()
              // console.log($("#client-button").html());
          });
          $("#series").on('change', function() {
              $.get( "{{ route('data.invoice.max') }}/" + this.value, function( data ) {
                  $("#inputNumber").val(parseInt(data));
                  // console.log($("#inputNumber").val);
              });
          });
          $("#date").on('change', function() {
              $.getJSON( "{{ route('data.exchange') }}/" + this.value, function( data ) {
                  $("#inputExchangeRate").val(data.rate);
              });

          })

          // $("#series").on('change', function() {
          //     $("#number").val = numbers[this.value];
          // })
      });
  </script>
@endpush

resources/views/invoices/index.blade.php
@extends('layouts.main')

@push('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endpush

@section('content')

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Facturi
      <small>Lista facturi emise</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Dashboard</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header with-border">

                  <a href="{{ route('invoices.create') }}" class="btn btn-success">Factura noua</a>


          </div>
          <!-- /.box-header -->
          <div class="box-body">

            <table class="table table-bordered" id="cars-table" width="100%">
              <thead>
              <tr>
                <th>Serie</th>
                <th>Numar</th>
                <th>Client</th>
                <th>Data</th>
                <th>Total RON</th>
                <th>Total EUR</th>
                <th>Actiuni</th>
              </tr>
              </thead>
            </table>

          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->

@endsection

@push('scripts')

  <!-- DataTables -->
  <script src="/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

  <!-- page script -->
  {{--<script>--}}
      {{--$(function () {--}}
          {{--// $('#example1').DataTable()--}}
          {{--$('#example1').DataTable({--}}
              {{--'paging'      : true,--}}
              {{--'lengthChange': false,--}}
              {{--// 'searching'   : false,--}}
              {{--// "columns": [--}}
              {{--//     { "searchable": false },--}}
              {{--//     null,--}}
              {{--//     null,--}}
              {{--//     null,--}}
              {{--//     null--}}
              {{--// ],--}}
              {{--'ordering'    : true,--}}
              {{--'info'        : true,--}}
              {{--'autoWidth'   : false,--}}
              {{--// 'filtering'   : true--}}
          {{--})--}}
      {{--})--}}
  {{--</script>--}}

  <script>
      $(function() {
          $('#cars-table').DataTable({
              processing: true,
              serverSide: true,
              ajax: '{!! route('data.invoices') !!}',
              columns: [
                  { data: 'series', name: 'series' },
                  { data: 'number', name: 'number' },
                  { data: 'name', name: 'clients.name' },
                  { data: 'date', name: 'date' },
                  { data: 'total_ron', name: 'total_ron' },
                  { data: 'total_eur', name: 'total_eur' },
                  { data: 'action', name: 'action' },
              ],
              // 'autoWidth'   : true,

              "scrollX": true,
              "order": [[ 3, "desc" ], [ 1, "desc" ]],
          });
      });
  </script>

@endpush